authors:
  zeutschler:
    name: Thomas Zeutschler
    description: Creator
    avatar: https://github.com/zeutschler.png
    url: https://github.com/Zeutschler
    reference_url: https://www.linkedin.com/in/thomas-zeutschler/
